In [15]:
import numpy as np

In [17]:
def step(sum):
    if sum>=0:
        return 1
    else:
        return 0
def perceptron(X,Y):
    l=0.1
    W=np.zeros(X.shape[1])
    b=np.array([0])
    for ep in range(10):
        for i in range(X.shape[0]):
            sum=np.dot(W,X[i])+b
            Y_pred=step(sum)
            E=Y[i]-Y_pred
            if E!=0:
                W=W+l*E*X[i]
                b=b+l*E
                print(W,b)
    return W,b

In [19]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([0,0,0,1])
l=0.1
W,b = perceptron(X,Y)
for i in range(X.shape[0]):
    sum=np.dot(W,X[i])+b
    Y_pred=step(sum)
    print(X[i],Y_pred,Y[i])

[0. 0.] [-0.1]
[0.1 0.1] [0.]
[0.1 0.1] [-0.1]
[0.1 0. ] [-0.2]
[0.2 0.1] [-0.1]
[0.2 0. ] [-0.2]
[0.1 0. ] [-0.3]
[0.2 0.1] [-0.2]
[0 0] 0 0
[0 1] 0 0
[1 0] 0 0
[1 1] 1 1


In [21]:
X=np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y=np.array([0,1,1,1,1,1,1,1])
l=0.1
W,b = perceptron(X,Y)
for i in range(X.shape[0]):
    sum=np.dot(W,X[i])+b
    Y_pred=step(sum)
    print(X[i],Y_pred,Y[i])

[0. 0. 0.] [-0.1]
[0.  0.  0.1] [0.]
[0.  0.  0.1] [-0.1]
[0.  0.1 0.1] [0.]
[0.  0.1 0.1] [-0.1]
[0.1 0.1 0.1] [0.]
[0.1 0.1 0.1] [-0.1]
[0 0 0] 0 0
[0 0 1] 1 1
[0 1 0] 1 1
[0 1 1] 1 1
[1 0 0] 1 1
[1 0 1] 1 1
[1 1 0] 1 1
[1 1 1] 1 1
