## AND gate perceptron model 

In [2]:
import numpy as np
def step(sum):
    if sum>=0:
        return 1
    return 0
def perceptron(X,Y):
    l=0.1
    W=np.zeros(X.shape[1])
    b=np.array(0)
    for ep in range(10):
        for i in range(X.shape[0]):
            sum=np.dot(W,X[i])+b
            y_pred=step(sum)
            E=Y[i]-y_pred
            if E!=0:
                W=W+l*E*X[i]
                b=b+l*E
                flag=1
            print(W,b)
        if flag==0:
            break
    return W,b
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([0,0,0,1])
W,b=perceptron(X,Y)
for i in range(X.shape[0]):
    sum=np.dot(W,X[i])+b
    Y_pred=step(sum)
    print(X[i],Y_pred,Y[i])

[0. 0.] -0.1
[0. 0.] -0.1
[0. 0.] -0.1
[0.1 0.1] 0.0
[0.1 0.1] -0.1
[0.1 0. ] -0.2
[0.1 0. ] -0.2
[0.2 0.1] -0.1
[0.2 0.1] -0.1
[0.2 0. ] -0.2
[0.1 0. ] -0.30000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.20000000000000004
[0.2 0.1] -0.2000000

In [2]:
import numpy as np
def step(sum):
    if sum>=0:
        return 1
    return 0
def perceptron(X,Y):
    l=0.1
    W=np.zeros(X.shape[1])
    b=np.array(0)
    for ep in range(10):
        for i in range(X.shape[0]):
            sum=np.dot(W,X[i])+b
            y_pred=step(sum)
            E=Y[i]-y_pred
            if E!=0:
                W=W+l*E*X[i]
                b=b+l*E
                flag=1
            print(W,b)
        if flag==0:
            break
    return W,b
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([0,1,1,1])
W,b=perceptron(X,Y)
for i in range(X.shape[0]):
    sum=np.dot(W,X[i])+b
    Y_pred=step(sum)
    print(X[i],Y_pred,Y[i])

[0. 0.] -0.1
[0.  0.1] 0.0
[0.  0.1] 0.0
[0.  0.1] 0.0
[0.  0.1] -0.1
[0.  0.1] -0.1
[0.1 0.1] 0.0
[0.1 0.1] 0.0
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0.1 0.1] -0.1
[0 0] 0 0
[0 1] 1 1
[1 0] 1 1
[1 1] 1 1


## 3 input OR gate perceptron model 

In [3]:
import numpy as np
def summation(e):
    if e>=0:
        return 1
    else:
        return 0
def perceptron(X,Y):
    W=np.zeros(X.shape[1])
    b=np.array(0)
    l=0.1
    for i in range(10):
        flag=0
        for i in range(X.shape[0]):
            sum=np.dot(W,X[i])+b
            y_pred=summation(sum)
            error=Y[i]-y_pred
            if error!=0:
                W=W+l*error*X[i]
                b=b+l*error
                flag=1
            print(W,b)
            if flag==0:
                break
    return W,b
X=np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y=np.array([0,1,1,1,1,1,1,1])
W,b=perceptron(X,Y)
for i in range(X.shape[0]):
    sum=np.dot(W,X[i])+b
    y_pred=summation(sum)
    print(X[i],y_pred,Y[i])

[0. 0. 0.] -0.1
[0.  0.  0.1] 0.0
[0.  0.  0.1] 0.0
[0.  0.  0.1] 0.0
[0.  0.  0.1] 0.0
[0.  0.  0.1] 0.0
[0.  0.  0.1] 0.0
[0.  0.  0.1] 0.0
[0.  0.  0.1] -0.1
[0.  0.  0.1] -0.1
[0.  0.1 0.1] 0.0
[0.  0.1 0.1] 0.0
[0.  0.1 0.1] 0.0
[0.  0.1 0.1] 0.0
[0.  0.1 0.1] 0.0
[0.  0.1 0.1] 0.0
[0.  0.1 0.1] -0.1
[0.  0.1 0.1] -0.1
[0.  0.1 0.1] -0.1
[0.  0.1 0.1] -0.1
[0.1 0.1 0.1] 0.0
[0.1 0.1 0.1] 0.0
[0.1 0.1 0.1] 0.0
[0.1 0.1 0.1] 0.0
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0.1 0.1 0.1] -0.1
[0 0 0] 0 0
[0 0 1] 1 1
[0 1 0] 1 1
[0 1 1] 1 1
[1 0 0] 1 1
[1 0 1] 1 1
[1 1 0] 1 1
[1 1 1] 1 1
