In [1]:
# ROLL NO:22341A0590
import tensorflow as tf

In [2]:
#creating tensors
scalar=tf.constant(42)
vector=tf.constant([1,2,3])
matrix=tf.constant([[1,2],[3,4]])
tensor_3d=tf.constant([[[1,2],[3,4],[5,6],[7,8]]])

print("Scalar: ",scalar)
print("Vector: ",vector)
print("Matrix:\n ",matrix)
print("3d tensor:\n ",tensor_3d)

Scalar:  tf.Tensor(42, shape=(), dtype=int32)
Vector:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix:
  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
3d tensor:
  tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]], shape=(1, 4, 2), dtype=int32)


In [3]:
#Attributes
print("Attributes of tensors:")
print("Shape of matrix:",matrix.shape)
print("Rank of 3d tensor:",tf.rank(tensor_3d))
print("Data type of vector:",vector.dtype)

Attributes of tensors:
Shape of matrix: (2, 2)
Rank of 3d tensor: tf.Tensor(3, shape=(), dtype=int32)
Data type of vector: <dtype: 'int32'>


In [4]:
#Arithmetic Operations
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
add_result=tf.add(a,b)
sub_result=tf.subtract(a,b)
mul_result=tf.multiply(a,b)
div_result=tf.divide(a,b)
print("Addition: ",add_result)
print("Subtraction",sub_result)
print("Elemnent wise multiplication: ",mul_result)
print("Division: ",div_result)

Addition:  tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Subtraction tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
Elemnent wise multiplication:  tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Division:  tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [5]:
#Reashaping and Slicing
t=tf.constant([1,2,3,4,5,6])
reshaped_tensor=tf.reshape(t,[2,3])
sliced_tensor=reshaped_tensor[:,:2]
print("Reshaped Tensor: ",reshaped_tensor)
print("Sliced Tensor: ",sliced_tensor)

Reshaped Tensor:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Sliced Tensor:  tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)


In [6]:
#Aggregation
matrix=tf.constant([[1,2],[3,4]])
sum_result=tf.reduce_sum(matrix,axis=1)
min_result=tf.reduce_min(matrix)
max_result=tf.reduce_max(matrix)
print("Sum of elements: ",sum_result)
print("Min of elements: ",min_result)
print("Max of elements:",max_result)

Sum of elements:  tf.Tensor([3 7], shape=(2,), dtype=int32)
Min of elements:  tf.Tensor(1, shape=(), dtype=int32)
Max of elements: tf.Tensor(4, shape=(), dtype=int32)


In [7]:
#Activation Functions
input_tensor = tf.constant([[-1.0, 0.0, 1.0], [2.0, -3.0, 4.0]]) 
relu_output = tf.nn.relu(input_tensor) 
sigmoid_output = tf.nn.sigmoid(input_tensor) 
print("ReLU Output:\n", relu_output) 
print("Sigmoid Output:\n", sigmoid_output)

ReLU Output:
 tf.Tensor(
[[0. 0. 1.]
 [2. 0. 4.]], shape=(2, 3), dtype=float32)
Sigmoid Output:
 tf.Tensor(
[[0.26894143 0.5        0.7310586 ]
 [0.8807971  0.04742587 0.98201376]], shape=(2, 3), dtype=float32)


In [8]:
x=tf.Variable(10.0)
with tf.GradientTape() as tape:
    y1=x**2
    y2=1/(1+tf.exp(-x))
print(tape.gradient(y2,x))


tf.Tensor(4.5395806e-05, shape=(), dtype=float32)
